[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "KoML-Docs"
authors = [{name = "Onion Kim", email = "hypothesis22@gmail.com"}]
dynamic = ["version", "description"]
